---
- name: create symlink from surface-tension to app dir
  file:
    src: "/vagrant"
    dest: "/var/www/html/surface-tension"
    state: link

- name: set selinux to permissive mode
  shell: "setenforce Permissive"

- name: install apache config
  template:
    src: apache.conf.j2
    dest: '/etc/httpd/conf.d/surface-tension.conf'
  notify: Reload Apache

